# Generated by Django 5.2 on 2025-05-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_equation_graph_config_graphconfig_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedgraph',
            name='config',
        ),
        migrations.RemoveField(
            model_name='savedgraph',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedEquation',
        ),
        migrations.DeleteModel(
            name='SavedGraph',
        ),
    ]
